import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  Source_Code_Pro, //
  Ubuntu,
  Lato,
  Open_Sans, // //
  Work_Sans, // //
  Inter, //
  Roboto,
  Inria_Sans, // //
  IBM_Plex_Sans, // //
  IBM_Plex_Mono, // //
  Poppins, // //
  Plus_Jakarta_Sans, //
  DM_Sans, // //
  Rubik, // //
  Fira_Code,
  Golos_Text, // //
  Radio_Canada, // //
  Meera_Inimai,
  //Rubik,
} from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Navbar from "@/components/custom/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Inter({
  variable: "--font-ibm-plex",
  subsets: ["latin"],
  weight: "400",
});

const montserrat = Work_Sans({
  variable: "--font-worksans",
  subsets: ["latin"],
  weight: "300",
});

const openSans = Fira_Code({
  variable: "--font-fira",
  subsets: ["latin"],
  weight: "300",
});

const lato = Inter({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: "300",
});

const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: "300",
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Goal Archive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${openSans.variable} ${lato.variable} ${ubuntu.variable} ${sourceCodePro.variable} ${roboto.variable}  antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
